// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQjJiLfcUPcAKTVJZgwwq7n-7i2VOaVRc',
    appId: '1:28193976233:web:bea990f5ea6cc76cfedeb8',
    messagingSenderId: '28193976233',
    projectId: 'najlepsza-knajpa-1',
    authDomain: 'najlepsza-knajpa-1.firebaseapp.com',
    storageBucket: 'najlepsza-knajpa-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYQXLy_tt0yxtdhKiNVoVOSB-MsmPVpVE',
    appId: '1:28193976233:android:4ac6b2f41165cec1fedeb8',
    messagingSenderId: '28193976233',
    projectId: 'najlepsza-knajpa-1',
    storageBucket: 'najlepsza-knajpa-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvUN2BmCDGgEB9d_9xtE-2mN-8tB0ViW8',
    appId: '1:28193976233:ios:bf001fb0bb4b77bffedeb8',
    messagingSenderId: '28193976233',
    projectId: 'najlepsza-knajpa-1',
    storageBucket: 'najlepsza-knajpa-1.appspot.com',
    iosBundleId: 'com.alexpawlowski.najlepszaKnajpa2',
  );
}
